version: 2

registries:
  defra:
    type: nuget-feed
    url: https://nuget.pkg.github.com/DEFRA/index.json
    token: ${{ secrets.DEPENDABOT_PAT }}

updates:
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/London"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
    allow:
      - dependency-type: direct
    registries: "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/London"