name: topics-and-queues-emulator

services:

  localstack:
    container_name: "sns-sqs-emulator"
    build:
      dockerfile: "./compose/Dockerfile.localstack"
    ports:
      - "4966:4566"
      - "4910-4959:4510-4559"
    environment:
      - SERVICES=s3,sns,sqs
