FROM localstack/localstack:4.3.0

WORKDIR "/"

EXPOSE 4566
EXPOSE 4510-4559

COPY ./compose/start-localstack.sh /etc/localstack/init/ready.d/
RUN chmod +x /etc/localstack/init/ready.d/start-localstack.sh

RUN addgroup -S nonrootgroup
RUN adduser -S nonrootuser -G nonrootgroup
RUN chown -R nonrootuser:nonrootgroup /etc/localstack/init/ready.d/start-localstack.sh

USER nonrootuser
