FROM localstack/localstack:4.14.0

WORKDIR "/"

EXPOSE 4566
EXPOSE 4510-4559

COPY ./compose/start-localstack.sh /etc/localstack/init/ready.d/
RUN chmod +x /etc/localstack/init/ready.d/start-localstack.sh