FROM localstack/localstack:4.3.0

WORKDIR "/"

EXPOSE 4566
EXPOSE 4510-4559

COPY ./compose/start-localstack.sh /etc/localstack/init/ready.d/

RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot

USER nonroot

RUN chmod +x /etc/localstack/init/ready.d/start-localstack.sh